set_property IOSTANDARD LVCMOS18 [get_ports clk_100M]
set_property PACKAGE_PIN E3 [get_ports clk_100M]
set_property IOSTANDARD LVCMOS18 [get_ports _rst]
set_property PACKAGE_PIN N17 [get_ports _rst]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {_rst_IBUF}]
set_property IOSTANDARD LVCMOS18 [get_ports _clk_RR]
set_property PACKAGE_PIN P18 [get_ports _clk_RR]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {_clk_RR_IBUF}]
set_property IOSTANDARD LVCMOS18 [get_ports _clk_F]
set_property PACKAGE_PIN P17 [get_ports _clk_F]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {_clk_F_IBUF}]
set_property IOSTANDARD LVCMOS18 [get_ports _clk_WB]
set_property PACKAGE_PIN R18 [get_ports _clk_WB]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {_clk_R_IBUF}]


set_property IOSTANDARD LVCMOS18 [get_ports operation]
set_property PACKAGE_PIN V5 [get_ports operation[3]]
set_property PACKAGE_PIN T4 [get_ports operation[2]]
set_property PACKAGE_PIN V6 [get_ports operation[1]]
set_property PACKAGE_PIN T5 [get_ports operation[0]]
set_property IOSTANDARD LVCMOS18 [get_ports R_addr_A]
set_property PACKAGE_PIN T6 [get_ports R_addr_A[4]]
set_property PACKAGE_PIN V7 [get_ports R_addr_A[3]]
set_property PACKAGE_PIN R8 [get_ports R_addr_A[2]]
set_property PACKAGE_PIN U9 [get_ports R_addr_A[1]]
set_property PACKAGE_PIN T9 [get_ports R_addr_A[0]]
set_property IOSTANDARD LVCMOS18 [get_ports R_addr_B]
set_property PACKAGE_PIN V10 [get_ports R_addr_B[4]]
set_property PACKAGE_PIN R10 [get_ports R_addr_B[3]]
set_property PACKAGE_PIN U11 [get_ports R_addr_B[2]]
set_property PACKAGE_PIN R11 [get_ports R_addr_B[1]]
set_property PACKAGE_PIN U12 [get_ports R_addr_B[0]]
set_property IOSTANDARD LVCMOS18 [get_ports Reg_Write]
set_property PACKAGE_PIN T13 [get_ports Reg_Write]
set_property IOSTANDARD LVCMOS18 [get_ports W_addr]
set_property PACKAGE_PIN V14 [get_ports W_addr[4]]
set_property PACKAGE_PIN T14 [get_ports W_addr[3]]
set_property PACKAGE_PIN V15 [get_ports W_addr[2]]
set_property PACKAGE_PIN R15 [get_ports W_addr[1]]
set_property PACKAGE_PIN U16 [get_ports W_addr[0]]


set_property IOSTANDARD LVCMOS18 [get_ports sel]
set_property PACKAGE_PIN C9 [get_ports sel[7]]
set_property PACKAGE_PIN C10 [get_ports sel[6]]
set_property PACKAGE_PIN D10 [get_ports sel[5]]
set_property PACKAGE_PIN C11 [get_ports sel[4]]
set_property PACKAGE_PIN M17 [get_ports sel[3]]
set_property PACKAGE_PIN J14 [get_ports sel[2]]
set_property PACKAGE_PIN K13 [get_ports sel[1]]
set_property PACKAGE_PIN P14 [get_ports sel[0]]

set_property IOSTANDARD LVCMOS18 [get_ports seg]
set_property PACKAGE_PIN F14 [get_ports seg[7]]
set_property PACKAGE_PIN N14 [get_ports seg[6]]
set_property PACKAGE_PIN J13 [get_ports seg[5]]
set_property PACKAGE_PIN G13 [get_ports seg[4]]
set_property PACKAGE_PIN F13 [get_ports seg[3]]
set_property PACKAGE_PIN G14 [get_ports seg[2]]
set_property PACKAGE_PIN M13 [get_ports seg[1]]
set_property PACKAGE_PIN H14 [get_ports seg[0]]

set_property IOSTANDARD LVCMOS18 [get_ports led]
set_property PACKAGE_PIN U6 [get_ports led[3]]
set_property PACKAGE_PIN U7 [get_ports led[2]]
set_property PACKAGE_PIN R7 [get_ports led[1]]
set_property PACKAGE_PIN T8 [get_ports led[0]]