set_property IOSTANDARD LVCMOS18 [get_ports clk_100M]
set_property PACKAGE_PIN E3 [get_ports clk_100M]

set_property IOSTANDARD LVCMOS18 [get_ports start]
set_property PACKAGE_PIN N17 [get_ports start]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {start_IBUF}]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property PACKAGE_PIN P18 [get_ports rst]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {rst_IBUF}]

set_property IOSTANDARD LVCMOS18 [get_ports stop]
set_property PACKAGE_PIN V5 [get_ports stop]
set_property IOSTANDARD LVCMOS18 [get_ports speedup]
set_property PACKAGE_PIN T4 [get_ports speedup[1]]
set_property PACKAGE_PIN V6 [get_ports speedup[0]]
set_property IOSTANDARD LVCMOS18 [get_ports pause]
set_property PACKAGE_PIN T5 [get_ports pause]

set_property IOSTANDARD LVCMOS18 [get_ports sel]
set_property PACKAGE_PIN C9 [get_ports sel[7]]
set_property PACKAGE_PIN C10 [get_ports sel[6]]
set_property PACKAGE_PIN D10 [get_ports sel[5]]
set_property PACKAGE_PIN C11 [get_ports sel[4]]
set_property PACKAGE_PIN M17 [get_ports sel[3]]
set_property PACKAGE_PIN J14 [get_ports sel[2]]
set_property PACKAGE_PIN K13 [get_ports sel[1]]
set_property PACKAGE_PIN P14 [get_ports sel[0]]

set_property IOSTANDARD LVCMOS18 [get_ports seg]
set_property PACKAGE_PIN F14 [get_ports seg[7]]
set_property PACKAGE_PIN N14 [get_ports seg[6]]
set_property PACKAGE_PIN J13 [get_ports seg[5]]
set_property PACKAGE_PIN G13 [get_ports seg[4]]
set_property PACKAGE_PIN F13 [get_ports seg[3]]
set_property PACKAGE_PIN G14 [get_ports seg[2]]
set_property PACKAGE_PIN M13 [get_ports seg[1]]
set_property PACKAGE_PIN H14 [get_ports seg[0]]