# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivadoproject/RISC_V_ZHZ.srcs/sources_1/ip/My_ROM/My_ROM.xci
# IP: The module: 'My_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivadoproject/RISC_V_ZHZ.srcs/sources_1/ip/My_ROM/My_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'My_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/vivadoproject/RISC_V_ZHZ.srcs/sources_1/ip/My_ROM/My_ROM.xci
# IP: The module: 'My_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivadoproject/RISC_V_ZHZ.srcs/sources_1/ip/My_ROM/My_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'My_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
