set_property IOSTANDARD LVCMOS18 [get_ports start]
set_property PACKAGE_PIN V5 [get_ports start]
set_property IOSTANDARD LVCMOS18 [get_ports pause]
set_property PACKAGE_PIN T4 [get_ports pause]
set_property IOSTANDARD LVCMOS18 [get_ports CLK]
set_property PACKAGE_PIN E3 [get_ports CLK]
set_property IOSTANDARD LVCMOS18 [get_ports car_wait]
set_property PACKAGE_PIN T5 [get_ports car_wait]
set_property IOSTANDARD LVCMOS18 [get_ports speedup]
set_property PACKAGE_PIN T6 [get_ports speedup[1]]
set_property PACKAGE_PIN V7 [get_ports speedup[0]]
set_property IOSTANDARD LVCMOS18 [get_ports d_m]
set_property PACKAGE_PIN R8 [get_ports d_m]


set_property IOSTANDARD LVCMOS18 [get_ports distance]
set_property PACKAGE_PIN U8 [get_ports distance[13]]
set_property PACKAGE_PIN T8 [get_ports distance[12]]
set_property PACKAGE_PIN V9 [get_ports distance[11]]
set_property PACKAGE_PIN T10 [get_ports distance[10]]
set_property PACKAGE_PIN V11 [get_ports distance[9]]
set_property PACKAGE_PIN T11 [get_ports distance[8]]
set_property PACKAGE_PIN V12 [get_ports distance[7]]
set_property PACKAGE_PIN R12 [get_ports distance[6]]
set_property PACKAGE_PIN U13 [get_ports distance[5]]
set_property PACKAGE_PIN R13 [get_ports distance[4]]
set_property PACKAGE_PIN U14 [get_ports distance[3]]
set_property PACKAGE_PIN T15 [get_ports distance[2]]
set_property PACKAGE_PIN V16 [get_ports distance[1]]
set_property PACKAGE_PIN T16 [get_ports distance[0]]


set_property IOSTANDARD LVCMOS18 [get_ports sel]
set_property PACKAGE_PIN C9 [get_ports sel[7]]
set_property PACKAGE_PIN C10 [get_ports sel[6]]
set_property PACKAGE_PIN D10 [get_ports sel[5]]
set_property PACKAGE_PIN C11 [get_ports sel[4]]
set_property PACKAGE_PIN M17 [get_ports sel[3]]
set_property PACKAGE_PIN J14 [get_ports sel[2]]
set_property PACKAGE_PIN K13 [get_ports sel[1]]
set_property PACKAGE_PIN P14 [get_ports sel[0]]
set_property IOSTANDARD LVCMOS18 [get_ports EN]
set_property PACKAGE_PIN V17 [get_ports EN]
set_property IOSTANDARD LVCMOS18 [get_ports seg]
set_property PACKAGE_PIN F14 [get_ports seg[7]]
set_property PACKAGE_PIN N14 [get_ports seg[6]]
set_property PACKAGE_PIN J13 [get_ports seg[5]]
set_property PACKAGE_PIN G13 [get_ports seg[4]]
set_property PACKAGE_PIN F13 [get_ports seg[3]]
set_property PACKAGE_PIN G14 [get_ports seg[2]]
set_property PACKAGE_PIN M13 [get_ports seg[1]]
set_property PACKAGE_PIN H14 [get_ports seg[0]]

